backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "prompts"
    label: "Prompts"
    folder: "_prompts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Card Main Title Text", name: "title", widget: "string" }
      - { label: "Category Dynamic Slug (No spaces, e.g., bike-news)", name: "category", widget: "string" }
      - { label: "Prompt Text", name: "prompt_text", widget: "text" }
      - { label: "Card Cover Image (URL)", name: "image_url", widget: "string" }
      - { label: "Card Description Subtext", name: "description", widget: "text", required: false }
      
